development:
  facebook_app_id: 285526178751158
  facebook_app_secret: ca750d3e19de995d7ea7545c0427eebc
  vkontakte_app_id: 6731047
  vkontakte_app_secret: ypApVD7GLD0P3rc05c9L

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
  vkontakte_app_id: <%= ENV["VK_APP_ID"] %> 6731047
  vkontakte_app_secret: <%= ENV["VK_APP_SECRET"] %> ypApVD7GLD0P3rc05c9L
