production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
  vkontakte_app_id: <%= ENV["VK_APP_ID"] %>
  vkontakte_app_secret: <%= ENV["VK_APP_SECRET"] %>
